id: A359B0540
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
type: translation
pechas:
- I5F59147B
- I7BDB213C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:02.814302
  last_modified_at: 2023-01-04 11:52:02.814315
  collections:
  - Fifth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5F59147B/9974: 3B98
  I7BDB213C/592A: 3B98
